on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@0.2.0
        with:
          version: 1.4.30
      - run: kotlin main.kts
